language: node_js
node_js:
- 6
- 5
- 4
before_script: npm run lint
deploy:
  provider: npm
  email: potz666@gmail.com
  api_key:
    secure: Y63lh/mLMc+N+pKjUg+4LrUZPb+b8Sc2cBjTL9Se3xdiHPME9WRKDhBKoXHVS7aRAtfN31zvMcD0aUjOUPlPJhspJVAFOvYhGCb7kuKdfUHarKBXd+42Eh2UhrEJ9vqYXg9MvZoZ54syz8MijKvIv5AVwjvt6ErJ5cuOZ7wgxzWW0xYvDMYyOM9mCidP+doWpK0DtsQ4Bul1BovWYJDSMrPpphRVcvPp+ZM92+3HaLtWXme2C1lpLmgMsYvt2O0a+DKeMoRE5DQxdedUcuEOMZ9CIYVTssgYDSGcd7m/CHZR7pnkP8he1IEq0um7wpQXHQiD0ZMYfW7yGESLpYQqL2YZYBUFyxGkFjhEmWBLstGIqu40nGiFJUiS5874/ZQDQK0JpS6JiPk8JdFA7419o08kr6JmOMp4ZlI/VP7YNsk+Pa+zvMaujA0IGmWB28e2V+U6i1SOLVqzKUVHWeSxhDXEG/o+O6ax1u8JJzUdqoPAlCYDjGctrYfdOogSyoHiaVDYAgTV9i+jjymA+RkmAtBDOvVAbqwLtupdz7iYKeAaqZ+PMkbztYcJyuuwrQJ4SY7x6Ney3i+Wprzvsdj8/WrrKk7gigp8lGVoaYLBS7S77fTUE0rke6g0zdG1yokoYNKDCN7L5aHoYaBE1yHxPfLIHAQLYpOUdp2qZLx3j3U=
  on:
    branch: master
    repo: eXigentCoder/swagger-spec-express
